export default {
  products: [
    {
      _id: "1",
      name: "Macbook Laptop",
      category: "computers",
      image: "/images/productone.png",
      price: 500,
      mark: "Apple",
      rating: 3.9,
      quantity: 12,
      availability: 10,
    },
    {
      _id: "2",
      name: "Samsung Tablet",
      category: "other",
      image: "/images/producttwo.png",
      price: 200,
      mark: "Samsung",
      rating: 4.1,
      quantity: 30,
    },
    {
      _id: "3",
      name: "Headphones Airpods ",
      category: "others",
      image: "/images/productthree.png",
      price: 100,
      mark: "Apple",
      rating: 3.4,
      quantity: 60,
      availability: 30,
    },
    {
      _id: "4",
      name: "XIAOMI 12 Pro",
      category: "smartphones",
      image: "/images/productfour.png",
      price: 600,
      mark: "Xiaomi",
      rating: 4.8,
      quantity: 43,
    },
    {
      _id: "5",
      name: "Huawei P50 PRO",
      category: "smartphones",
      image: "/images/productfive.png",
      price: 600,
      mark: "Huawei",
      rating: 4.0,
      quantity: 28,
      availability: 39,
    },
    {
      _id: "6",
      name: "IPhone 13 Pro",
      category: "smartphones",
      image: "/images/productsix.png",
      price: 800,
      mark: "Apple",
      rating: 4.7,
      quantity: 37,
    },
  ],
};
